
version: '3'

services:
  back:
    build: ./back/
    container_name: guig_api
    environment:
      - REPO_PATH=/usr/src/demo
      - DATABASE_URI=sqlite:///data.db
    ports:
      - "8081:80"
  front:
    build: ./front/
    container_name: guig_vue
    ports:
      - "8080:8080"